# Generated by Django 3.1.7 on 2021-03-19 06:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=256)),
                ('item_description', models.TextField(blank=True)),
                ('item_quantity', models.PositiveIntegerField(default=0)),
                ('reason', models.TextField(blank=True)),
                ('status', models.IntegerField(choices=[(0, 'draft'), (1, 'submitted'), (2, 'processing'), (3, 'approved'), (4, 'rejected')], default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person', models.CharField(max_length=256)),
                ('contact_number', models.CharField(default='00000000', max_length=8, validators=[django.core.validators.RegexValidator('(8[1-8][0-9]{6}|9[0-8][0-9]{6})', 'Invalid phone number.')])),
                ('supplier_name', models.CharField(max_length=256)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('document', models.FileField(max_length=131072, upload_to='uploads/', validators=[utils.validators.file_validator])),
                ('remarks', models.TextField()),
                ('selected', models.BooleanField(default=False)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='quotations.quotation')),
            ],
            options={
                'unique_together': {('quotation', 'supplier_name')},
            },
        ),
    ]
