# Generated by Django 3.1.7 on 2021-03-19 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('min_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('max_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('order', models.PositiveSmallIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('status', models.IntegerField(blank=True, choices=[(0, 'unprocessed'), (1, 'approved'), (2, 'rejected')], default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotations.quotation')),
            ],
            options={
                'unique_together': {('quotation', 'order'), ('quotation', 'group')},
            },
        ),
        migrations.CreateModel(
            name='ProcessGroupPrecedence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotations.process')),
            ],
            options={
                'unique_together': {('process', 'group'), ('process', 'order')},
            },
        ),
        migrations.AddField(
            model_name='process',
            name='groups_order',
            field=models.ManyToManyField(through='quotations.ProcessGroupPrecedence', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='approvers_order',
            field=models.ManyToManyField(through='quotations.ProcessStage', to='auth.Group'),
        ),
    ]
