# Generated by Django 3.1.7 on 2021-03-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.IntegerField(blank=True, choices=[(0, 'Treasurer'), (1, 'Financial Executive'), (2, 'Financial Secretary'), (3, 'NUSSU President')], default=0),
        ),
    ]
